### ISSUE TITLE
Сверстать страницу с интерфейсом создания/редактирования задачи

### ISSUE THREAD

**Issue by yawningstudent** [OSLL/asm_web_debug#177]
Сверстать страницу с интерфейсом (создание задачи, заполнение параметров задачи, сохранение задачи, открытие задачи по id), используя flask template. Маршрут до страницы - /edit_task

Результат: PR в отдельной ветке

**Comment by ImSOLty** [comment]
### Интерфейс
![1](https://user-images.githubusercontent.com/48078801/158029059-6536534d-ddcf-4915-a75b-c000bcd86601.png)
![2](https://user-images.githubusercontent.com/48078801/158029061-f87e961c-2689-4629-9ce7-0b00a068e585.png)
![3](https://user-images.githubusercontent.com/48078801/158029063-3cb73ae6-e7a2-4718-9242-7a831f2d67fb.png)
