### ISSUE TITLE
Актуализировать сущность Task в соответствии с Wiki проекта

### ISSUE THREAD

**Issue by Artiesy** [OSLL/asm_web_debug#207]
https://github.com/OSLL/asm_web_debug/wiki/Architecture

Сущность "параметры" (в вики tasks -> parameters) представляет из себя ожидаемые значения регистров (адрес и значение - пара "ключ-значение"), которые требуются для решения задачи. Таких элементов может может быть несколько, явно parameters имеет типа Map

**Comment by yawningstudent** [comment]
Так же необходимо задавать входные параметры регистров. Требуется уточнение у Дмитрия

**Comment by Artiesy** [comment]
parameters - конфигурации задачи. Эти параметры могут иметь разный вид - регистры/память/output - поэтому поле сделано словарем, чтобы добавить немного гибкости. Значит делаем paramters - словарь со структурой:

```
{
    output: "Example expected output",
    registry: {
        eax: 123,
        abd: 222,
        ecx: 111,
        edbx: 1234
    }
}
```
